module.exports = {
  displayName: 'users',
  preset: 'ts-jest',
  testEnvironment: 'node',
  maxWorkers: 1,
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
  },
  testMatch: ['**/*.spec.ts', '**/*.test.ts'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.spec.ts',
    '!src/**/*.test.ts',
    '!src/**/__fixtures__/**',
    '!src/**/__mocks__/**',
    '!src/main.ts',
  ],
  coverageDirectory: './coverage',
  moduleNameMapper: {
    '^@app/users/(.*)$': '<rootDir>/src/$1',
    '^@app/balance/(.*)$': '<rootDir>/../../apps/balance/src/$1',
    '^@lib/shared/(.*)$': '<rootDir>/../../libs/shared/src/$1',
    '^@lib/lib-balance/(.*)$': '<rootDir>/../../libs/lib-balance/src/$1',
    '^@lib/lib-bonus/(.*)$': '<rootDir>/../../libs/lib-bonus/src/$1',
    '^@lib/lib-games/(.*)$': '<rootDir>/../../libs/lib-games/src/$1',
    '^@lib/lib-affise/(.*)$': '<rootDir>/../../libs/lib-affise/src/$1',
    '^@lib/lib-dengage/(.*)$': '<rootDir>/../../libs/lib-dengage/src/$1',
    '^@lib/lib-exchange-rate/(.*)$': '<rootDir>/../../libs/lib-exchange-rate/src/$1',
    '^@lib/shared$': '<rootDir>/../../libs/shared/src',
    '^@lib/lib-balance$': '<rootDir>/../../libs/lib-balance/src',
    '^@lib/lib-bonus$': '<rootDir>/../../libs/lib-bonus/src',
    '^@lib/lib-games$': '<rootDir>/../../libs/lib-games/src',
    '^@lib/lib-affise$': '<rootDir>/../../libs/lib-affise/src',
    '^@lib/lib-dengage$': '<rootDir>/../../libs/lib-dengage/src',
    '^@lib/lib-exchange-rate$': '<rootDir>/../../libs/lib-exchange-rate/src',
    '^@prisma/users$': '<rootDir>/../../prisma/users/generated',
  },
  setupFilesAfterEnv: ['<rootDir>/../../jest.setup.ts'],
};

