module.exports = {
  displayName: 'users-integration',
  preset: 'ts-jest',
  testEnvironment: 'node',
  maxWorkers: 1,
  detectOpenHandles: true,
  forceExit: true,
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx'],
  transform: {
    '^.+\\.(ts|tsx)$': 'ts-jest',
  },
  testMatch: ['**/*.integration.spec.ts'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.unit.spec.ts',
    '!src/**/*.integration.spec.ts',
    '!src/**/*.e2e.spec.ts',
    '!src/**/__fixtures__/**',
    '!src/**/__mocks__/**',
    '!src/main.ts',
  ],
  coverageDirectory: './coverage/integration',
  moduleNameMapper: {
    '^@app/player-service/(.*)$': '<rootDir>/src/$1',
    '^@app/auth-service/(.*)$': '<rootDir>/../../apps/balance/src/$1',
    '^@lib/shared/(.*)$': '<rootDir>/../../libs/shared/src/$1',
    '^@lib/lib-building/(.*)$': '<rootDir>/../../libs/lib-balance/src/$1',
    '^@lib/lib-combat-progress/(.*)$': '<rootDir>/../../libs/lib-bonus/src/$1',
    '^@lib/lib-game-server/(.*)$': '<rootDir>/../../libs/lib-games/src/$1',
    '^@lib/lib-affise/(.*)$': '<rootDir>/../../libs/lib-affise/src/$1',
    '^@lib/lib-dengage/(.*)$': '<rootDir>/../../libs/lib-dengage/src/$1',
    '^@lib/lib-exchange-rate/(.*)$': '<rootDir>/../../libs/lib-exchange-rate/src/$1',
    '^@lib/shared$': '<rootDir>/../../libs/shared/src',
    '^@lib/lib-building$': '<rootDir>/../../libs/lib-balance/src',
    '^@lib/lib-combat-progress$': '<rootDir>/../../libs/lib-bonus/src',
    '^@lib/lib-game-server$': '<rootDir>/../../libs/lib-games/src',
    '^@lib/lib-affise$': '<rootDir>/../../libs/lib-affise/src',
    '^@lib/lib-dengage$': '<rootDir>/../../libs/lib-dengage/src',
    '^@lib/lib-exchange-rate$': '<rootDir>/../../libs/lib-exchange-rate/src',
    '^@prisma/meta$': '<rootDir>/../../prisma/users/generated',
  },
  setupFilesAfterEnv: ['<rootDir>/../../jest.setup.ts'],
  testTimeout: 30000,
};

